// Curated SEO content roadmap for CAFEPASTE.
//
// Each entry describes a planned page across all 7 supported languages.
// The admin Roadmap UI ([src/pages/admin/seo/SeoRoadmap.tsx]) reads this file
// and shows a grid: each row is a planned page, each column is a language.
// Cells reflect status from the seo_pages table (published / draft / missing)
// and a single click on a missing cell triggers AI draft generation
// pre-filled with that entry's target_query + audience_hint.
//
// Strategy: BRAND-FIRST. No competitor-comparison entries — CAFEPASTE
// positions as the category-defining authority (per user feedback). Page
// types are scoped to: homepage, guide (Glossary playbook), solution
// (Personas playbook), use-case (Examples playbook), location (Locations
// playbook). Comparison type stays in the codebase but is intentionally
// absent from this roadmap.
//
// To add/remove pages: edit this file, commit. The Roadmap UI updates
// automatically — no DB migration needed.

import type { SupportedLang } from './seoConfig';
import type { SeoPageType } from '../services/seoPageService';

export type Playbook = 'Glossary' | 'Personas' | 'Examples' | 'Locations' | 'Homepage' | 'Dictionary';
export type Tier = 0 | 1 | 2 | 3;

export interface RoadmapEntry {
    /** Stable identifier — used for React keys and roadmap → seo_pages lookup. */
    id: string;
    type: SeoPageType;
    tier: Tier;
    playbook: Playbook;
    /** Display label for the roadmap row (Turkish, since admin is Turkish). */
    label: string;
    /** Per-language slug. Homepage is always 'home' in every language. */
    slug: Record<SupportedLang, string>;
    /** Per-language target query — fed to AI draft as the primary keyword. */
    target_query: Record<SupportedLang, string>;
    /** Single audience hint, language-agnostic. Helps AI keep tone right. */
    audience_hint?: string;
    /** Optional editor note shown in the roadmap row. */
    notes?: string;
}

const PATH_PREFIX: Record<Exclude<SeoPageType, 'homepage'>, string> = {
    comparison: 'compare',
    guide: 'guides',
    solution: 'solutions',
    glossary: 'glossary',
};

/** Build the public URL path a roadmap entry's published page would live at,
 *  for a given language. Used by the roadmap UI to render preview links. */
export function pathForEntry(entry: RoadmapEntry, lang: SupportedLang): string {
    if (entry.type === 'homepage') return `/${lang}`;
    const prefix = PATH_PREFIX[entry.type as Exclude<SeoPageType, 'homepage'>];
    return `/${lang}/${prefix}/${entry.slug[lang]}`;
}

// ----------------------------------------------------------------------------
// Tier 1 — Brand Authority Core
// 6 entries × 7 langs = 42 pages. First production wave.
// ----------------------------------------------------------------------------

const TIER_1: RoadmapEntry[] = [
    {
        id: 'homepage',
        type: 'homepage',
        tier: 1,
        playbook: 'Homepage',
        label: 'Ana sayfa (CAFEPASTE)',
        slug: { tr: 'home', en: 'home', de: 'home', fr: 'home', es: 'home', it: 'home', pl: 'home' },
        target_query: {
            tr: 'CAFEPASTE içecek art makinesi',
            en: 'CAFEPASTE beverage art creator',
            de: 'CAFEPASTE Getränke-Druck-Maschine',
            fr: 'CAFEPASTE machine à art de boissons',
            es: 'CAFEPASTE máquina de arte para bebidas',
            it: 'CAFEPASTE macchina per beverage art',
            pl: 'CAFEPASTE maszyna do beverage art',
        },
        audience_hint: 'Kategori tanımlayıcı ana sayfa; 4 segmenti (kafe, otel, etkinlik, ajans) kapsar',
        notes: 'Slug her dilde "home" sabit. Landing page bu satırı kullanır.',
    },
    {
        id: 'guide-what-is-beverage-art',
        type: 'guide',
        tier: 1,
        playbook: 'Glossary',
        label: 'İçecek art makinesi nedir',
        slug: {
            tr: 'icecek-art-makinesi-nedir',
            en: 'what-is-a-beverage-art-creator',
            de: 'was-ist-eine-getraenke-druck-maschine',
            fr: 'quest-ce-quune-machine-art-boisson',
            es: 'que-es-una-maquina-de-arte-para-bebidas',
            it: 'cose-una-macchina-per-beverage-art',
            pl: 'co-to-jest-maszyna-do-beverage-art',
        },
        target_query: {
            tr: 'içecek art makinesi nedir',
            en: 'what is a beverage art creator',
            de: 'was ist eine Getränke Druck Maschine',
            fr: 'qu’est-ce qu’une machine à art de boisson',
            es: 'qué es una máquina de arte para bebidas',
            it: 'cos’è una macchina per beverage art',
            pl: 'co to jest maszyna do beverage art',
        },
        audience_hint: 'Kategoriyi öğrenmek isteyen kafe sahibi, etkinlik organizatörü',
    },
    {
        id: 'guide-how-it-works',
        type: 'guide',
        tier: 1,
        playbook: 'Glossary',
        label: 'Latte art baskı nasıl çalışır',
        slug: {
            tr: 'latte-art-baski-nasil-calisir',
            en: 'how-latte-art-printing-works',
            de: 'wie-latte-art-druck-funktioniert',
            fr: 'comment-fonctionne-impression-latte-art',
            es: 'como-funciona-la-impresion-de-latte-art',
            it: 'come-funziona-stampa-latte-art',
            pl: 'jak-dziala-druk-latte-art',
        },
        target_query: {
            tr: 'latte art baskı nasıl çalışır',
            en: 'how does latte art printing work',
            de: 'wie funktioniert Latte Art Druck',
            fr: 'comment fonctionne l’impression latte art',
            es: 'cómo funciona la impresión de latte art',
            it: 'come funziona la stampa latte art',
            pl: 'jak działa druk latte art',
        },
        audience_hint: 'Teknik merak — barista, kafe operatörü, satın alma karar vericisi',
    },
    {
        id: 'solution-cafe',
        type: 'solution',
        tier: 1,
        playbook: 'Personas',
        label: 'Kafe çözümü',
        slug: {
            tr: 'kafe',
            en: 'cafe',
            de: 'cafe',
            fr: 'cafe',
            es: 'cafeteria',
            it: 'caffetteria',
            pl: 'kawiarnia',
        },
        target_query: {
            tr: 'kafe için latte art makinesi',
            en: 'beverage art creator for cafes',
            de: 'Latte Art Drucker für Cafés',
            fr: 'machine à art de café pour cafés',
            es: 'máquina de arte para cafeterías',
            it: 'macchina per latte art per caffetterie',
            pl: 'maszyna do latte art dla kawiarni',
        },
        audience_hint: 'Kafe / restoran zinciri sahipleri, operasyon müdürleri — günlük kullanım, marka',
    },
    {
        id: 'solution-hotel',
        type: 'solution',
        tier: 1,
        playbook: 'Personas',
        label: 'Otel çözümü',
        slug: {
            tr: 'otel',
            en: 'hotel',
            de: 'hotel',
            fr: 'hotel',
            es: 'hotel',
            it: 'hotel',
            pl: 'hotel',
        },
        target_query: {
            tr: 'otel için kahve kişiselleştirme',
            en: 'hotel coffee personalization',
            de: 'Hotel Kaffee Personalisierung',
            fr: 'personnalisation café hôtel',
            es: 'personalización café hotel',
            it: 'personalizzazione caffè hotel',
            pl: 'personalizacja kawy hotel',
        },
        audience_hint: 'Otel & resort F&B yöneticileri — misafir deneyimi, marka standartı',
    },
    {
        id: 'solution-wedding-event',
        type: 'solution',
        tier: 1,
        playbook: 'Personas',
        label: 'Düğün / etkinlik çözümü',
        slug: {
            tr: 'etkinlik-dugun',
            en: 'wedding-event',
            de: 'hochzeit-event',
            fr: 'mariage-evenement',
            es: 'boda-evento',
            it: 'matrimonio-evento',
            pl: 'wesele-event',
        },
        target_query: {
            tr: 'düğün için kahve baskı makinesi',
            en: 'wedding coffee printer rental',
            de: 'Hochzeit Kaffeedrucker Vermietung',
            fr: 'location imprimante café mariage',
            es: 'alquiler impresora café boda',
            it: 'noleggio stampante caffè matrimonio',
            pl: 'wynajem drukarki do kawy na wesele',
        },
        audience_hint: 'Düğün/etkinlik organizatörleri, catering şirketleri — kiralama modeli',
    },
];

// ----------------------------------------------------------------------------
// Tier 2 — Category Expansion
// 5 entries × 7 langs = 35 pages. Second wave.
// ----------------------------------------------------------------------------

const TIER_2: RoadmapEntry[] = [
    {
        id: 'guide-printing-technology',
        type: 'guide',
        tier: 2,
        playbook: 'Glossary',
        label: 'Kahve baskı teknolojisi',
        slug: {
            tr: 'kahve-uzerine-baski-teknolojisi',
            en: 'coffee-printing-technology',
            de: 'kaffee-druck-technologie',
            fr: 'technologie-impression-cafe',
            es: 'tecnologia-impresion-cafe',
            it: 'tecnologia-stampa-caffe',
            pl: 'technologia-druku-kawa',
        },
        target_query: {
            tr: 'kahve baskı teknolojisi',
            en: 'coffee printing technology',
            de: 'Kaffee Drucktechnologie',
            fr: 'technologie d’impression de café',
            es: 'tecnología de impresión de café',
            it: 'tecnologia di stampa del caffè',
            pl: 'technologia druku na kawie',
        },
        audience_hint: 'Teknik karar vericisi — yenilebilir mürekkep, çözünürlük, gıda güvenliği',
    },
    {
        id: 'guide-wedding-coffee-bar',
        type: 'guide',
        tier: 2,
        playbook: 'Glossary',
        label: 'Düğün kahve bar rehberi',
        slug: {
            tr: 'dugun-kahve-bar-rehberi',
            en: 'wedding-coffee-bar-guide',
            de: 'hochzeit-kaffee-bar-leitfaden',
            fr: 'guide-bar-cafe-mariage',
            es: 'guia-bar-cafe-boda',
            it: 'guida-bar-caffe-matrimonio',
            pl: 'przewodnik-bar-kawowy-wesele',
        },
        target_query: {
            tr: 'düğün kahve bar fikirleri',
            en: 'wedding coffee bar ideas',
            de: 'Hochzeit Kaffeebar Ideen',
            fr: 'idées bar à café mariage',
            es: 'ideas bar de café boda',
            it: 'idee bar caffè matrimonio',
            pl: 'pomysły na bar kawowy na wesele',
        },
        audience_hint: 'Düğün çifti + organizatör — ilham + uygulama rehberi',
    },
    {
        id: 'solution-marketing-agency',
        type: 'solution',
        tier: 2,
        playbook: 'Personas',
        label: 'Pazarlama ajansı çözümü',
        slug: {
            tr: 'pazarlama-ajansi',
            en: 'marketing-agency',
            de: 'marketing-agentur',
            fr: 'agence-marketing',
            es: 'agencia-marketing',
            it: 'agenzia-marketing',
            pl: 'agencja-marketingowa',
        },
        target_query: {
            tr: 'marka aktivasyonu kahve baskı',
            en: 'brand activation coffee printing',
            de: 'Markenaktivierung Kaffeedruck',
            fr: 'activation marque impression café',
            es: 'activación de marca impresión café',
            it: 'attivazione brand stampa caffè',
            pl: 'aktywacja marki druk kawy',
        },
        audience_hint: 'Marka müdürleri, ajans yöneticileri — pop-up, etkinlik aktivasyonu, deneyimsel pazarlama',
    },
    {
        id: 'use-case-logo-printing',
        type: 'solution',
        tier: 2,
        playbook: 'Examples',
        label: 'Logo baskı kullanımı',
        slug: {
            tr: 'logo-baski',
            en: 'logo-printing',
            de: 'logo-druck',
            fr: 'impression-logo',
            es: 'impresion-logo',
            it: 'stampa-logo',
            pl: 'druk-logo',
        },
        target_query: {
            tr: 'kahve üzerine logo baskı',
            en: 'logo printing on coffee',
            de: 'Logo Druck auf Kaffee',
            fr: 'impression de logo sur café',
            es: 'impresión de logo en café',
            it: 'stampa logo su caffè',
            pl: 'druk logo na kawie',
        },
        audience_hint: 'Markalı içecek isteyen kurumsal kullanıcı, kafe sahibi',
        notes: 'Use-case sayfalar şu an "solution" tipi olarak kayıtlı (use-case ayrı bir tip eklenmediği için)',
    },
    {
        id: 'use-case-photo-printing',
        type: 'solution',
        tier: 2,
        playbook: 'Examples',
        label: 'Foto baskı kullanımı',
        slug: {
            tr: 'foto-baski',
            en: 'photo-printing',
            de: 'foto-druck',
            fr: 'impression-photo',
            es: 'impresion-foto',
            it: 'stampa-foto',
            pl: 'druk-zdjec',
        },
        target_query: {
            tr: 'kahve üzerine fotoğraf baskı',
            en: 'photo printing on coffee',
            de: 'Foto Druck auf Kaffee',
            fr: 'impression photo sur café',
            es: 'impresión foto en café',
            it: 'stampa foto su caffè',
            pl: 'druk zdjęć na kawie',
        },
        audience_hint: 'Düğün, doğum günü, etkinlik için kişiselleştirilmiş içecek isteyenler',
    },
    {
        id: 'guide-cafe-latte-art-cost',
        type: 'guide',
        tier: 2,
        playbook: 'Glossary',
        label: 'Kafe için latte art makinesi maliyeti',
        slug: {
            tr: 'kafe-latte-art-makinesi-maliyeti',
            en: 'cafe-latte-art-machine-cost',
            de: 'cafe-latte-art-maschine-kosten',
            fr: 'cout-machine-latte-art-cafe',
            es: 'costo-maquina-latte-art-cafeteria',
            it: 'costo-macchina-latte-art-caffetteria',
            pl: 'koszt-maszyny-latte-art-kawiarnia',
        },
        target_query: {
            tr: 'kafe latte art makinesi maliyeti',
            en: 'cafe latte art machine cost',
            de: 'Café Latte Art Maschine Kosten',
            fr: 'coût machine latte art café',
            es: 'costo máquina latte art cafetería',
            it: 'costo macchina latte art caffetteria',
            pl: 'koszt maszyny latte art kawiarnia',
        },
        audience_hint: 'Kafe sahipleri, satın alma karar vericisi — yatırım dönüşü ve TCO',
    },
    {
        id: 'guide-hotel-breakfast-experience',
        type: 'guide',
        tier: 2,
        playbook: 'Glossary',
        label: 'Otel kahvaltısında kişiselleştirilmiş kahve',
        slug: {
            tr: 'otel-kahvalti-kisisellestirilmis-kahve',
            en: 'hotel-breakfast-personalized-coffee',
            de: 'hotel-fruehstueck-personalisierter-kaffee',
            fr: 'petit-dejeuner-hotel-cafe-personnalise',
            es: 'desayuno-hotel-cafe-personalizado',
            it: 'colazione-hotel-caffe-personalizzato',
            pl: 'sniadanie-hotel-kawa-personalizowana',
        },
        target_query: {
            tr: 'otel kahvaltısında kişiselleştirilmiş kahve',
            en: 'hotel breakfast personalized coffee',
            de: 'Hotel Frühstück personalisierter Kaffee',
            fr: 'café personnalisé petit-déjeuner hôtel',
            es: 'café personalizado desayuno hotel',
            it: 'caffè personalizzato colazione hotel',
            pl: 'spersonalizowana kawa śniadanie hotel',
        },
        audience_hint: 'Otel F&B yöneticileri — misafir deneyimi diferansiasyonu',
    },
    {
        id: 'guide-wedding-pricing',
        type: 'guide',
        tier: 2,
        playbook: 'Glossary',
        label: 'Düğün kahve bar fiyatlandırma rehberi',
        slug: {
            tr: 'dugun-kahve-bar-fiyatlandirma',
            en: 'wedding-coffee-bar-pricing',
            de: 'hochzeit-kaffee-bar-preise',
            fr: 'tarifs-bar-cafe-mariage',
            es: 'precios-bar-cafe-boda',
            it: 'prezzi-bar-caffe-matrimonio',
            pl: 'ceny-bar-kawowy-wesele',
        },
        target_query: {
            tr: 'düğün kahve bar fiyat',
            en: 'wedding coffee bar pricing',
            de: 'Hochzeit Kaffeebar Preise',
            fr: 'prix bar à café mariage',
            es: 'precio bar de café boda',
            it: 'prezzo bar caffè matrimonio',
            pl: 'cena baru kawowego na wesele',
        },
        audience_hint: 'Düğün organizatörleri — bütçe planlaması, paket karşılaştırma',
    },
    {
        id: 'use-case-corporate-branding',
        type: 'solution',
        tier: 2,
        playbook: 'Examples',
        label: 'Kurumsal markalama kullanımı',
        slug: {
            tr: 'kurumsal-marka-baski',
            en: 'corporate-branding-coffee',
            de: 'unternehmensmarken-kaffeedruck',
            fr: 'impression-cafe-marque-entreprise',
            es: 'impresion-cafe-marca-corporativa',
            it: 'stampa-caffe-brand-aziendale',
            pl: 'druk-kawy-marka-firmowa',
        },
        target_query: {
            tr: 'kahve üzerine kurumsal logo baskı',
            en: 'corporate logo coffee printing',
            de: 'Firmenlogo Kaffeedruck',
            fr: 'impression café logo entreprise',
            es: 'impresión café logo empresa',
            it: 'stampa caffè logo aziendale',
            pl: 'druk kawy logo firmowe',
        },
        audience_hint: 'Marka yöneticileri, kurumsal iletişim — günlük ofis kullanımı',
    },
    {
        id: 'guide-agency-activation',
        type: 'guide',
        tier: 2,
        playbook: 'Glossary',
        label: 'Marka aktivasyonu için kahve baskı',
        slug: {
            tr: 'marka-aktivasyonu-kahve-baski-rehberi',
            en: 'brand-activation-coffee-printing-guide',
            de: 'markenaktivierung-kaffeedruck-leitfaden',
            fr: 'guide-activation-marque-impression-cafe',
            es: 'guia-activacion-marca-impresion-cafe',
            it: 'guida-attivazione-brand-stampa-caffe',
            pl: 'przewodnik-aktywacja-marki-druk-kawy',
        },
        target_query: {
            tr: 'marka aktivasyonu kahve baskı rehberi',
            en: 'brand activation coffee printing guide',
            de: 'Markenaktivierung Kaffeedruck Leitfaden',
            fr: 'guide activation marque impression café',
            es: 'guía activación marca impresión café',
            it: 'guida attivazione brand stampa caffè',
            pl: 'przewodnik aktywacja marki druk kawy',
        },
        audience_hint: 'Ajans yöneticileri — pop-up, lansman, deneyimsel pazarlama',
    },
    {
        id: 'use-case-cafe-menu',
        type: 'solution',
        tier: 2,
        playbook: 'Examples',
        label: 'Kafe menü farklılaştırma',
        slug: {
            tr: 'kafe-menu-farklilastirma',
            en: 'cafe-menu-differentiation',
            de: 'cafe-menue-differenzierung',
            fr: 'differenciation-menu-cafe',
            es: 'diferenciacion-menu-cafeteria',
            it: 'differenziazione-menu-caffetteria',
            pl: 'roznicowanie-menu-kawiarnia',
        },
        target_query: {
            tr: 'kafe menü farklılaştırma',
            en: 'cafe menu differentiation',
            de: 'Café Menü Differenzierung',
            fr: 'différenciation menu café',
            es: 'diferenciación menú cafetería',
            it: 'differenziazione menu caffetteria',
            pl: 'różnicowanie menu w kawiarni',
        },
        audience_hint: 'Kafe sahipleri — yeni müşteri çekme, sosyal medya paylaşımı',
    },
    {
        id: 'guide-roi-cafe',
        type: 'guide',
        tier: 2,
        playbook: 'Glossary',
        label: 'Kafede latte art makinesi ROI',
        slug: {
            tr: 'kafe-latte-art-makinesi-roi',
            en: 'cafe-latte-art-machine-roi',
            de: 'cafe-latte-art-maschine-roi',
            fr: 'roi-machine-latte-art-cafe',
            es: 'roi-maquina-latte-art-cafeteria',
            it: 'roi-macchina-latte-art-caffetteria',
            pl: 'roi-maszyna-latte-art-kawiarnia',
        },
        target_query: {
            tr: 'latte art makinesi geri dönüş süresi',
            en: 'latte art machine ROI',
            de: 'Latte Art Maschine ROI',
            fr: 'ROI machine latte art',
            es: 'ROI máquina latte art',
            it: 'ROI macchina latte art',
            pl: 'ROI maszyny latte art',
        },
        audience_hint: 'Karar vericisi — yatırım gerekçesi, geri ödeme periyodu',
    },
    {
        id: 'use-case-hotel-event',
        type: 'solution',
        tier: 2,
        playbook: 'Examples',
        label: 'Otel etkinlik & toplantı kullanımı',
        slug: {
            tr: 'otel-etkinlik-toplanti',
            en: 'hotel-event-meeting',
            de: 'hotel-event-meeting',
            fr: 'hotel-evenement-reunion',
            es: 'hotel-evento-reunion',
            it: 'hotel-evento-riunione',
            pl: 'hotel-event-spotkanie',
        },
        target_query: {
            tr: 'otel etkinlik kahve baskı',
            en: 'hotel event coffee printing',
            de: 'Hotel Event Kaffeedruck',
            fr: 'impression café événement hôtel',
            es: 'impresión café evento hotel',
            it: 'stampa caffè evento hotel',
            pl: 'druk kawy event hotelowy',
        },
        audience_hint: 'Otel etkinlik müdürleri — konferans, gala, kurumsal ağırlama',
    },
    {
        id: 'guide-catering-business',
        type: 'guide',
        tier: 2,
        playbook: 'Glossary',
        label: 'Catering işletmeleri için kahve baskı',
        slug: {
            tr: 'catering-isletmeleri-kahve-baski',
            en: 'catering-business-coffee-printing',
            de: 'catering-unternehmen-kaffeedruck',
            fr: 'traiteur-impression-cafe',
            es: 'catering-impresion-cafe',
            it: 'catering-stampa-caffe',
            pl: 'catering-druk-kawy',
        },
        target_query: {
            tr: 'catering kahve baskı hizmeti',
            en: 'catering coffee printing service',
            de: 'Catering Kaffeedruck Service',
            fr: 'service impression café traiteur',
            es: 'servicio impresión café catering',
            it: 'servizio stampa caffè catering',
            pl: 'usługa druku kawy catering',
        },
        audience_hint: 'Catering işletmecileri — hizmet portföyü genişletme, kiralama modeli',
    },
];

// ----------------------------------------------------------------------------
// Tier 3 — Long-tail & Geo
// Examples + Locations playbooks. Third wave.
// ----------------------------------------------------------------------------

const TIER_3: RoadmapEntry[] = [
    // Glossary terms — short citable definitions. Targets "X nedir / what is X"
    // long-tail queries and feeds AI assistants concise authoritative answers.
    {
        id: 'glossary-latte-art',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Latte Art',
        slug: { tr: 'latte-art', en: 'latte-art', de: 'latte-art', fr: 'latte-art', es: 'latte-art', it: 'latte-art', pl: 'latte-art' },
        target_query: {
            tr: 'latte art nedir',
            en: 'what is latte art',
            de: 'was ist latte art',
            fr: 'qu\'est-ce que le latte art',
            es: 'qué es latte art',
            it: 'cos\'è il latte art',
            pl: 'co to jest latte art',
        },
        audience_hint: 'İlk kez duyan kafe sahibi / kahve meraklısı — kategoriyi tanımla',
    },
    {
        id: 'glossary-edible-ink',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Yenilebilir mürekkep',
        slug: { tr: 'yenilebilir-murekkep', en: 'edible-ink', de: 'essbare-tinte', fr: 'encre-comestible', es: 'tinta-comestible', it: 'inchiostro-commestibile', pl: 'jadalny-tusz' },
        target_query: {
            tr: 'yenilebilir mürekkep nedir',
            en: 'what is edible ink',
            de: 'was ist essbare Tinte',
            fr: 'qu\'est-ce que l\'encre comestible',
            es: 'qué es la tinta comestible',
            it: 'cos\'è l\'inchiostro commestibile',
            pl: 'co to jest jadalny tusz',
        },
        audience_hint: 'Gıda güvenliği endişesi olan alıcı — sertifika + güvenlik detayları',
    },
    {
        id: 'glossary-beverage-printing',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'İçecek baskısı',
        slug: { tr: 'icecek-baskisi', en: 'beverage-printing', de: 'getraenkedruck', fr: 'impression-boisson', es: 'impresion-bebidas', it: 'stampa-bevande', pl: 'druk-na-napojach' },
        target_query: {
            tr: 'içecek baskısı nedir',
            en: 'what is beverage printing',
            de: 'was ist Getränkedruck',
            fr: 'qu\'est-ce que l\'impression sur boisson',
            es: 'qué es la impresión en bebidas',
            it: 'cos\'è la stampa su bevande',
            pl: 'co to jest druk na napojach',
        },
        audience_hint: 'Kategoriyi en geniş şekilde tanımlayan terim — entry-level alıcı',
    },
    {
        id: 'glossary-foam-printing',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Köpük baskısı',
        slug: { tr: 'kopuk-baskisi', en: 'foam-printing', de: 'schaum-druck', fr: 'impression-mousse', es: 'impresion-espuma', it: 'stampa-schiuma', pl: 'druk-na-piance' },
        target_query: {
            tr: 'köpük baskısı nedir',
            en: 'what is foam printing',
            de: 'was ist Schaumdruck',
            fr: 'qu\'est-ce que l\'impression sur mousse',
            es: 'qué es la impresión en espuma',
            it: 'cos\'è la stampa sulla schiuma',
            pl: 'co to jest druk na piance',
        },
        audience_hint: 'Teknik merak — köpük yüzeyine baskı nasıl tutar',
    },

    {
        id: 'use-case-qr-printing',
        type: 'solution',
        tier: 3,
        playbook: 'Examples',
        label: 'QR kod baskı kullanımı',
        slug: {
            tr: 'qr-kod-baski',
            en: 'qr-code-printing',
            de: 'qr-code-druck',
            fr: 'impression-qr-code',
            es: 'impresion-qr',
            it: 'stampa-qr-code',
            pl: 'druk-kodow-qr',
        },
        target_query: {
            tr: 'kahve üzerine QR kod baskı',
            en: 'QR code coffee printing',
            de: 'QR Code Kaffeedruck',
            fr: 'impression QR code café',
            es: 'impresión QR en café',
            it: 'stampa QR code caffè',
            pl: 'druk kodu QR na kawie',
        },
        audience_hint: 'Dijital pazarlamacılar — kampanya yönlendirme, müşteri etkileşimi',
    },
    {
        id: 'use-case-birthday',
        type: 'solution',
        tier: 3,
        playbook: 'Examples',
        label: 'Doğum günü organizasyonu',
        slug: {
            tr: 'dogum-gunu-organizasyonu',
            en: 'birthday-events',
            de: 'geburtstag-events',
            fr: 'anniversaire-evenement',
            es: 'cumpleanos-eventos',
            it: 'compleanno-eventi',
            pl: 'urodziny-event',
        },
        target_query: {
            tr: 'doğum günü kahve baskısı',
            en: 'birthday coffee printing',
            de: 'Geburtstag Kaffeedruck',
            fr: 'impression café anniversaire',
            es: 'impresión café cumpleaños',
            it: 'stampa caffè compleanno',
            pl: 'druk kawy urodziny',
        },
        audience_hint: 'Bireysel / butik etkinlik organizasyonu',
    },
    {
        id: 'use-case-corporate-events',
        type: 'solution',
        tier: 3,
        playbook: 'Examples',
        label: 'Kurumsal etkinlik kullanımı',
        slug: {
            tr: 'kurumsal-etkinlik',
            en: 'corporate-events',
            de: 'firmenevents',
            fr: 'evenement-entreprise',
            es: 'evento-corporativo',
            it: 'evento-aziendale',
            pl: 'event-korporacyjny',
        },
        target_query: {
            tr: 'kurumsal etkinlik kahve baskı',
            en: 'corporate event coffee printing',
            de: 'Firmenevent Kaffeedruck',
            fr: 'impression café événement entreprise',
            es: 'impresión café evento corporativo',
            it: 'stampa caffè evento aziendale',
            pl: 'druk kawy event korporacyjny',
        },
        audience_hint: 'Kurumsal etkinlik organizatörleri — konferans, lansman, gala',
    },
    {
        id: 'tech-edible-ink',
        type: 'guide',
        tier: 3,
        playbook: 'Glossary',
        label: 'Yenilebilir mürekkep güvenliği',
        slug: {
            tr: 'yenilebilir-murekep-guvenligi',
            en: 'edible-ink-food-safety',
            de: 'essbare-tinte-lebensmittelsicherheit',
            fr: 'encre-comestible-securite-alimentaire',
            es: 'tinta-comestible-seguridad-alimentaria',
            it: 'inchiostro-commestibile-sicurezza-alimentare',
            pl: 'jadalny-tusz-bezpieczenstwo',
        },
        target_query: {
            tr: 'yenilebilir mürekkep güvenliği',
            en: 'edible ink food safety',
            de: 'essbare Tinte Lebensmittelsicherheit',
            fr: 'encre comestible sécurité alimentaire',
            es: 'tinta comestible seguridad alimentaria',
            it: 'inchiostro commestibile sicurezza alimentare',
            pl: 'jadalny tusz bezpieczeństwo',
        },
        audience_hint: 'Gıda güvenliği endişesi olan kafe sahipleri, sağlık denetçileri',
    },
    {
        id: 'tech-software-app',
        type: 'guide',
        tier: 3,
        playbook: 'Glossary',
        label: 'Yazılım & uygulama',
        slug: {
            tr: 'yazilim-uygulama',
            en: 'software-app',
            de: 'software-app',
            fr: 'logiciel-application',
            es: 'software-aplicacion',
            it: 'software-app',
            pl: 'oprogramowanie-aplikacja',
        },
        target_query: {
            tr: 'kahve baskı uygulaması',
            en: 'coffee printer app',
            de: 'Kaffeedrucker App',
            fr: 'application imprimante café',
            es: 'aplicación impresora café',
            it: 'app stampante caffè',
            pl: 'aplikacja drukarki kawy',
        },
        audience_hint: 'Teknik karar vericisi — operasyon kolaylığı, eğitim',
    },

    // ---- 20 sözlük (glossary) terimleri ----
    {
        id: 'glossary-espresso',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Espresso',
        slug: { tr: 'espresso', en: 'espresso', de: 'espresso', fr: 'espresso', es: 'espresso', it: 'espresso', pl: 'espresso' },
        target_query: {
            tr: 'espresso nedir', en: 'what is espresso', de: 'was ist espresso',
            fr: 'qu\'est-ce que l\'espresso', es: 'qué es el espresso',
            it: 'cos\'è l\'espresso', pl: 'co to jest espresso',
        },
        audience_hint: 'Kahve dünyasına giren kullanıcı — kategori terimi',
    },
    {
        id: 'glossary-crema',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Crema',
        slug: { tr: 'crema', en: 'crema', de: 'crema', fr: 'crema', es: 'crema', it: 'crema', pl: 'crema' },
        target_query: {
            tr: 'crema nedir', en: 'what is crema', de: 'was ist crema',
            fr: 'qu\'est-ce que la crema', es: 'qué es la crema',
            it: 'cos\'è la crema', pl: 'co to jest crema',
        },
        audience_hint: 'Barista, kafe sahibi — baskı yüzeyi olarak crema önemi',
    },
    {
        id: 'glossary-cappuccino',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Cappuccino',
        slug: { tr: 'cappuccino', en: 'cappuccino', de: 'cappuccino', fr: 'cappuccino', es: 'cappuccino', it: 'cappuccino', pl: 'cappuccino' },
        target_query: {
            tr: 'cappuccino nedir', en: 'what is cappuccino', de: 'was ist cappuccino',
            fr: 'qu\'est-ce que le cappuccino', es: 'qué es el cappuccino',
            it: 'cos\'è il cappuccino', pl: 'co to jest cappuccino',
        },
        audience_hint: 'Genel kullanıcı — köpük yüzeyi baskıya uygun mu',
    },
    {
        id: 'glossary-microfoam',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Mikroköpük',
        slug: { tr: 'mikrokopuk', en: 'microfoam', de: 'mikroschaum', fr: 'micromousse', es: 'microespuma', it: 'microschiuma', pl: 'mikropianka' },
        target_query: {
            tr: 'mikroköpük nedir', en: 'what is microfoam', de: 'was ist Mikroschaum',
            fr: 'qu\'est-ce que la micromousse', es: 'qué es la microespuma',
            it: 'cos\'è la microschiuma', pl: 'co to jest mikropianka',
        },
        audience_hint: 'Barista, kafe sahibi — kaliteli baskı için köpük yapısı',
    },
    {
        id: 'glossary-ristretto',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Ristretto',
        slug: { tr: 'ristretto', en: 'ristretto', de: 'ristretto', fr: 'ristretto', es: 'ristretto', it: 'ristretto', pl: 'ristretto' },
        target_query: {
            tr: 'ristretto nedir', en: 'what is ristretto', de: 'was ist ristretto',
            fr: 'qu\'est-ce que le ristretto', es: 'qué es el ristretto',
            it: 'cos\'è il ristretto', pl: 'co to jest ristretto',
        },
        audience_hint: 'Kahve meraklısı — espresso varyasyonu',
    },
    {
        id: 'glossary-flat-white',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Flat White',
        slug: { tr: 'flat-white', en: 'flat-white', de: 'flat-white', fr: 'flat-white', es: 'flat-white', it: 'flat-white', pl: 'flat-white' },
        target_query: {
            tr: 'flat white nedir', en: 'what is flat white', de: 'was ist flat white',
            fr: 'qu\'est-ce que le flat white', es: 'qué es el flat white',
            it: 'cos\'è il flat white', pl: 'co to jest flat white',
        },
        audience_hint: 'Kafe sahibi — menü çeşitliliği, baskıya uygun içecekler',
    },
    {
        id: 'glossary-macchiato',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Macchiato',
        slug: { tr: 'macchiato', en: 'macchiato', de: 'macchiato', fr: 'macchiato', es: 'macchiato', it: 'macchiato', pl: 'macchiato' },
        target_query: {
            tr: 'macchiato nedir', en: 'what is macchiato', de: 'was ist macchiato',
            fr: 'qu\'est-ce que le macchiato', es: 'qué es el macchiato',
            it: 'cos\'è il macchiato', pl: 'co to jest macchiato',
        },
        audience_hint: 'Kahve meraklısı — espresso varyasyonu',
    },
    {
        id: 'glossary-mocha',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Mocha',
        slug: { tr: 'mocha', en: 'mocha', de: 'mocha', fr: 'mocha', es: 'mocha', it: 'mocha', pl: 'mocha' },
        target_query: {
            tr: 'mocha nedir', en: 'what is mocha', de: 'was ist mocha',
            fr: 'qu\'est-ce que le mocha', es: 'qué es el mocha',
            it: 'cos\'è il mocha', pl: 'co to jest mocha',
        },
        audience_hint: 'Kafe sahibi — çikolata + kahve içecek kategorisi',
    },
    {
        id: 'glossary-affogato',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Affogato',
        slug: { tr: 'affogato', en: 'affogato', de: 'affogato', fr: 'affogato', es: 'affogato', it: 'affogato', pl: 'affogato' },
        target_query: {
            tr: 'affogato nedir', en: 'what is affogato', de: 'was ist affogato',
            fr: 'qu\'est-ce que l\'affogato', es: 'qué es el affogato',
            it: 'cos\'è l\'affogato', pl: 'co to jest affogato',
        },
        audience_hint: 'Kafe sahibi — dondurmalı kahve sunumu',
    },
    {
        id: 'glossary-cold-brew',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Cold Brew',
        slug: { tr: 'cold-brew', en: 'cold-brew', de: 'cold-brew', fr: 'cold-brew', es: 'cold-brew', it: 'cold-brew', pl: 'cold-brew' },
        target_query: {
            tr: 'cold brew nedir', en: 'what is cold brew', de: 'was ist cold brew',
            fr: 'qu\'est-ce que le cold brew', es: 'qué es el cold brew',
            it: 'cos\'è il cold brew', pl: 'co to jest cold brew',
        },
        audience_hint: 'Kafe sahibi — soğuk içecek baskı uygulaması',
    },
    {
        id: 'glossary-barista',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Barista',
        slug: { tr: 'barista', en: 'barista', de: 'barista', fr: 'barista', es: 'barista', it: 'barista', pl: 'barista' },
        target_query: {
            tr: 'barista nedir', en: 'what is a barista', de: 'was ist ein Barista',
            fr: 'qu\'est-ce qu\'un barista', es: 'qué es un barista',
            it: 'cos\'è un barista', pl: 'kto to jest barista',
        },
        audience_hint: 'Kafe sahibi, işe alımcı — meslek tanımı + baskı asistanı pozisyonu',
    },
    {
        id: 'glossary-coffee-art',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Coffee Art',
        slug: { tr: 'coffee-art', en: 'coffee-art', de: 'coffee-art', fr: 'coffee-art', es: 'coffee-art', it: 'coffee-art', pl: 'coffee-art' },
        target_query: {
            tr: 'coffee art nedir', en: 'what is coffee art', de: 'was ist coffee art',
            fr: 'qu\'est-ce que le coffee art', es: 'qué es el coffee art',
            it: 'cos\'è il coffee art', pl: 'co to jest coffee art',
        },
        audience_hint: 'Genel kullanıcı — kategori umbrella terimi',
    },
    {
        id: 'glossary-3d-coffee-printer',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: '3D Kahve Yazıcısı',
        slug: { tr: '3d-kahve-yazicisi', en: '3d-coffee-printer', de: '3d-kaffeedrucker', fr: 'imprimante-cafe-3d', es: 'impresora-cafe-3d', it: 'stampante-caffe-3d', pl: 'drukarka-kawy-3d' },
        target_query: {
            tr: '3d kahve yazıcısı nedir', en: 'what is a 3d coffee printer',
            de: 'was ist ein 3D Kaffeedrucker', fr: 'qu\'est-ce qu\'une imprimante café 3D',
            es: 'qué es una impresora de café 3d', it: 'cos\'è una stampante caffè 3d',
            pl: 'co to jest drukarka do kawy 3d',
        },
        audience_hint: 'Teknik merak — kategoriye 3D printing açısı',
    },
    {
        id: 'glossary-food-grade-ink',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Gıda Sınıfı Mürekkep',
        slug: { tr: 'gida-sinifi-murekkep', en: 'food-grade-ink', de: 'lebensmittelechte-tinte', fr: 'encre-alimentaire', es: 'tinta-alimentaria', it: 'inchiostro-alimentare', pl: 'tusz-spozywczy' },
        target_query: {
            tr: 'gıda sınıfı mürekkep nedir', en: 'what is food grade ink',
            de: 'was ist lebensmittelechte Tinte', fr: 'qu\'est-ce que l\'encre alimentaire',
            es: 'qué es la tinta alimentaria', it: 'cos\'è l\'inchiostro alimentare',
            pl: 'co to jest tusz spożywczy',
        },
        audience_hint: 'Gıda güvenliği endişesi olan alıcı — sertifikalar',
    },
    {
        id: 'glossary-pull-shot',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Pull Shot',
        slug: { tr: 'pull-shot', en: 'pull-shot', de: 'pull-shot', fr: 'pull-shot', es: 'pull-shot', it: 'pull-shot', pl: 'pull-shot' },
        target_query: {
            tr: 'pull shot nedir', en: 'what is pull shot', de: 'was ist pull shot',
            fr: 'qu\'est-ce qu\'un pull shot', es: 'qué es pull shot',
            it: 'cos\'è il pull shot', pl: 'co to jest pull shot',
        },
        audience_hint: 'Barista — espresso çekim terminolojisi',
    },
    {
        id: 'glossary-tamper',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Tamper',
        slug: { tr: 'tamper', en: 'tamper', de: 'tamper', fr: 'tamper', es: 'tamper', it: 'tamper', pl: 'tamper' },
        target_query: {
            tr: 'tamper nedir', en: 'what is a tamper', de: 'was ist ein Tamper',
            fr: 'qu\'est-ce qu\'un tamper', es: 'qué es un tamper',
            it: 'cos\'è un tamper', pl: 'co to jest tamper',
        },
        audience_hint: 'Barista, kafe ekipman alıcısı — ekipman terimi',
    },
    {
        id: 'glossary-portafilter',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Portafilter',
        slug: { tr: 'portafilter', en: 'portafilter', de: 'siebtraeger', fr: 'porte-filtre', es: 'portafiltro', it: 'portafiltro', pl: 'kolba' },
        target_query: {
            tr: 'portafilter nedir', en: 'what is a portafilter',
            de: 'was ist ein Siebträger', fr: 'qu\'est-ce qu\'un porte-filtre',
            es: 'qué es un portafiltro', it: 'cos\'è un portafiltro',
            pl: 'co to jest kolba',
        },
        audience_hint: 'Barista, kafe ekipman alıcısı — espresso makinesi parçası',
    },
    {
        id: 'glossary-stencil',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Stensil (Şablon)',
        slug: { tr: 'kahve-stensil', en: 'coffee-stencil', de: 'kaffee-schablone', fr: 'pochoir-cafe', es: 'plantilla-cafe', it: 'stencil-caffe', pl: 'szablon-kawowy' },
        target_query: {
            tr: 'kahve stensili nedir', en: 'what is a coffee stencil',
            de: 'was ist eine Kaffeeschablone', fr: 'qu\'est-ce qu\'un pochoir café',
            es: 'qué es una plantilla café', it: 'cos\'è uno stencil caffè',
            pl: 'co to jest szablon do kawy',
        },
        audience_hint: 'Kafe sahibi — geleneksel yöntem vs makine baskısı karşılaştırması',
    },
    {
        id: 'glossary-coffee-printing',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Kahve Baskısı',
        slug: { tr: 'kahve-baskisi', en: 'coffee-printing', de: 'kaffeedruck', fr: 'impression-cafe', es: 'impresion-cafe', it: 'stampa-caffe', pl: 'druk-kawowy' },
        target_query: {
            tr: 'kahve baskısı nedir', en: 'what is coffee printing',
            de: 'was ist Kaffeedruck', fr: 'qu\'est-ce que l\'impression café',
            es: 'qué es la impresión en café', it: 'cos\'è la stampa caffè',
            pl: 'co to jest druk kawowy',
        },
        audience_hint: 'Genel kullanıcı — kategori girişi',
    },
    {
        id: 'glossary-selfie-coffee',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Selfie Kahve',
        slug: { tr: 'selfie-kahve', en: 'selfie-coffee', de: 'selfie-kaffee', fr: 'selfie-cafe', es: 'selfie-cafe', it: 'selfie-caffe', pl: 'selfie-kawa' },
        target_query: {
            tr: 'selfie kahve nedir', en: 'what is selfie coffee',
            de: 'was ist Selfie Kaffee', fr: 'qu\'est-ce que le selfie café',
            es: 'qué es el selfie café', it: 'cos\'è il selfie caffè',
            pl: 'co to jest selfie kawa',
        },
        audience_hint: 'Kafe sahibi — sosyal medya viral konsept',
    },

    // ---- 10 long-tail use-case / sektörel kullanım ----
    {
        id: 'use-case-cafe-instagram',
        type: 'solution',
        tier: 3,
        playbook: 'Examples',
        label: 'Kafede Instagram için viral içerik',
        slug: {
            tr: 'kafe-instagram-viral-icerik',
            en: 'cafe-instagram-viral-content',
            de: 'cafe-instagram-viraler-content',
            fr: 'cafe-instagram-contenu-viral',
            es: 'cafeteria-instagram-contenido-viral',
            it: 'caffetteria-instagram-contenuto-virale',
            pl: 'kawiarnia-instagram-viralna-tresc',
        },
        target_query: {
            tr: 'kafede Instagram için ne yapılır',
            en: 'cafe Instagram content ideas',
            de: 'Café Instagram Content Ideen',
            fr: 'idées contenu Instagram café',
            es: 'ideas contenido Instagram cafetería',
            it: 'idee contenuto Instagram caffetteria',
            pl: 'pomysły na treści Instagram kawiarnia',
        },
        audience_hint: 'Kafe sahibi, sosyal medya yöneticisi — viral içerik üretimi',
    },
    {
        id: 'use-case-baby-shower',
        type: 'solution',
        tier: 3,
        playbook: 'Examples',
        label: 'Baby shower organizasyonu',
        slug: {
            tr: 'baby-shower-kahve-baski',
            en: 'baby-shower-coffee-printing',
            de: 'babyparty-kaffeedruck',
            fr: 'baby-shower-impression-cafe',
            es: 'baby-shower-impresion-cafe',
            it: 'baby-shower-stampa-caffe',
            pl: 'baby-shower-druk-kawy',
        },
        target_query: {
            tr: 'baby shower kahve baskı',
            en: 'baby shower coffee printing',
            de: 'Babyparty Kaffeedruck',
            fr: 'impression café baby shower',
            es: 'impresión café baby shower',
            it: 'stampa caffè baby shower',
            pl: 'druk kawy baby shower',
        },
        audience_hint: 'Aileler, etkinlik organizatörleri — özel gün kişiselleştirme',
    },
    {
        id: 'use-case-graduation',
        type: 'solution',
        tier: 3,
        playbook: 'Examples',
        label: 'Mezuniyet kutlamaları',
        slug: {
            tr: 'mezuniyet-kahve-baski',
            en: 'graduation-coffee-printing',
            de: 'abschlussfeier-kaffeedruck',
            fr: 'remise-diplome-impression-cafe',
            es: 'graduacion-impresion-cafe',
            it: 'laurea-stampa-caffe',
            pl: 'absolutorium-druk-kawy',
        },
        target_query: {
            tr: 'mezuniyet kahve baskı',
            en: 'graduation coffee printing',
            de: 'Abschlussfeier Kaffeedruck',
            fr: 'impression café remise de diplôme',
            es: 'impresión café graduación',
            it: 'stampa caffè laurea',
            pl: 'druk kawy absolutorium',
        },
        audience_hint: 'Üniversite, aile — özel kutlama kişiselleştirme',
    },
    {
        id: 'use-case-product-launch',
        type: 'solution',
        tier: 3,
        playbook: 'Examples',
        label: 'Ürün lansmanı etkinliği',
        slug: {
            tr: 'urun-lansmani-kahve-baski',
            en: 'product-launch-coffee-printing',
            de: 'produktlaunch-kaffeedruck',
            fr: 'lancement-produit-impression-cafe',
            es: 'lanzamiento-producto-impresion-cafe',
            it: 'lancio-prodotto-stampa-caffe',
            pl: 'premiera-produktu-druk-kawy',
        },
        target_query: {
            tr: 'ürün lansmanı kahve baskı',
            en: 'product launch coffee printing',
            de: 'Produktlaunch Kaffeedruck',
            fr: 'impression café lancement produit',
            es: 'impresión café lanzamiento producto',
            it: 'stampa caffè lancio prodotto',
            pl: 'druk kawy premiera produktu',
        },
        audience_hint: 'Marka müdürleri — lansman aktivasyonu, basın etkinliği',
    },
    {
        id: 'use-case-trade-show',
        type: 'solution',
        tier: 3,
        playbook: 'Examples',
        label: 'Fuar ve sergi standı',
        slug: {
            tr: 'fuar-standi-kahve-baski',
            en: 'trade-show-coffee-printing',
            de: 'messestand-kaffeedruck',
            fr: 'salon-impression-cafe',
            es: 'feria-impresion-cafe',
            it: 'fiera-stampa-caffe',
            pl: 'targi-druk-kawy',
        },
        target_query: {
            tr: 'fuar standı kahve baskı',
            en: 'trade show coffee printing',
            de: 'Messestand Kaffeedruck',
            fr: 'impression café salon professionnel',
            es: 'impresión café feria',
            it: 'stampa caffè fiera',
            pl: 'druk kawy targi',
        },
        audience_hint: 'B2B pazarlamacılar — stand ziyaretçisi çekme, lead toplama',
    },
    {
        id: 'use-case-engagement',
        type: 'solution',
        tier: 3,
        playbook: 'Examples',
        label: 'Nişan ve söz organizasyonu',
        slug: {
            tr: 'nisan-kahve-baski',
            en: 'engagement-coffee-printing',
            de: 'verlobung-kaffeedruck',
            fr: 'fiancailles-impression-cafe',
            es: 'compromiso-impresion-cafe',
            it: 'fidanzamento-stampa-caffe',
            pl: 'zareczyny-druk-kawy',
        },
        target_query: {
            tr: 'nişan kahve baskı',
            en: 'engagement coffee printing',
            de: 'Verlobung Kaffeedruck',
            fr: 'impression café fiançailles',
            es: 'impresión café compromiso',
            it: 'stampa caffè fidanzamento',
            pl: 'druk kawy zaręczyny',
        },
        audience_hint: 'Çiftler, etkinlik organizatörleri — küçük çaplı özel etkinlik',
    },
    {
        id: 'use-case-restaurant',
        type: 'solution',
        tier: 3,
        playbook: 'Examples',
        label: 'Restoran misafir deneyimi',
        slug: {
            tr: 'restoran-kahve-baski',
            en: 'restaurant-coffee-printing',
            de: 'restaurant-kaffeedruck',
            fr: 'restaurant-impression-cafe',
            es: 'restaurante-impresion-cafe',
            it: 'ristorante-stampa-caffe',
            pl: 'restauracja-druk-kawy',
        },
        target_query: {
            tr: 'restoran kahve baskı',
            en: 'restaurant coffee printing',
            de: 'Restaurant Kaffeedruck',
            fr: 'impression café restaurant',
            es: 'impresión café restaurante',
            it: 'stampa caffè ristorante',
            pl: 'druk kawy restauracja',
        },
        audience_hint: 'Restoran sahipleri — yemek sonrası deneyim, marka hatırlatması',
    },
    {
        id: 'use-case-bakery',
        type: 'solution',
        tier: 3,
        playbook: 'Examples',
        label: 'Pastane ve fırın kullanımı',
        slug: {
            tr: 'pastane-kahve-baski',
            en: 'bakery-coffee-printing',
            de: 'baeckerei-kaffeedruck',
            fr: 'patisserie-impression-cafe',
            es: 'pasteleria-impresion-cafe',
            it: 'pasticceria-stampa-caffe',
            pl: 'cukiernia-druk-kawy',
        },
        target_query: {
            tr: 'pastane kahve baskı',
            en: 'bakery coffee printing',
            de: 'Bäckerei Kaffeedruck',
            fr: 'impression café pâtisserie',
            es: 'impresión café pastelería',
            it: 'stampa caffè pasticceria',
            pl: 'druk kawy cukiernia',
        },
        audience_hint: 'Pastane sahipleri — kahve eşliğinde kişiselleştirilmiş sunum',
    },
    {
        id: 'use-case-coworking',
        type: 'solution',
        tier: 3,
        playbook: 'Examples',
        label: 'Coworking ofis kullanımı',
        slug: {
            tr: 'coworking-kahve-baski',
            en: 'coworking-coffee-printing',
            de: 'coworking-kaffeedruck',
            fr: 'coworking-impression-cafe',
            es: 'coworking-impresion-cafe',
            it: 'coworking-stampa-caffe',
            pl: 'coworking-druk-kawy',
        },
        target_query: {
            tr: 'coworking ofis kahve baskı',
            en: 'coworking office coffee printing',
            de: 'Coworking Büro Kaffeedruck',
            fr: 'impression café coworking',
            es: 'impresión café coworking',
            it: 'stampa caffè coworking',
            pl: 'druk kawy coworking',
        },
        audience_hint: 'Coworking işletmecileri — üye deneyimi, etkinlik günleri',
    },
    {
        id: 'use-case-festival',
        type: 'solution',
        tier: 3,
        playbook: 'Examples',
        label: 'Festival ve konser aktivasyonu',
        slug: {
            tr: 'festival-kahve-baski',
            en: 'festival-coffee-printing',
            de: 'festival-kaffeedruck',
            fr: 'festival-impression-cafe',
            es: 'festival-impresion-cafe',
            it: 'festival-stampa-caffe',
            pl: 'festiwal-druk-kawy',
        },
        target_query: {
            tr: 'festival kahve baskı aktivasyon',
            en: 'festival coffee printing activation',
            de: 'Festival Kaffeedruck Aktivierung',
            fr: 'activation impression café festival',
            es: 'activación impresión café festival',
            it: 'attivazione stampa caffè festival',
            pl: 'aktywacja druk kawy festiwal',
        },
        audience_hint: 'Etkinlik sponsorları, ajans — büyük ölçekli marka deneyimi',
    },

    // ------------------------------------------------------------------------
    // Rakip-terim glossary'leri (kategori arama trafiği yakalama)
    // Bu 7 entry, sektörde rakiplerin ranklediği jenerik kategori isimlerini
    // hedefler: "coffee printer", "latte art printer", "cocktail printer", vs.
    // Her sayfa kısa, ansiklopedik tanım + CAFEPASTE'i o kategorinin
    // kategori-tanımlayıcı markası olarak konumlandırır (rakip ismi ANMAZ —
    // STRICT FACTUAL RULES gereği).
    // ------------------------------------------------------------------------
    {
        id: 'glossary-coffee-printer',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Coffee Printer / Kahve Yazıcısı',
        slug: {
            tr: 'kahve-yazicisi',
            en: 'coffee-printer',
            de: 'kaffee-drucker',
            fr: 'imprimante-cafe',
            es: 'impresora-de-cafe',
            it: 'stampante-caffe',
            pl: 'drukarka-do-kawy',
        },
        target_query: {
            tr: 'kahve yazıcısı nedir',
            en: 'what is a coffee printer',
            de: 'was ist ein Kaffeedrucker',
            fr: 'qu\'est-ce qu\'une imprimante à café',
            es: 'qué es una impresora de café',
            it: 'cos\'è una stampante per caffè',
            pl: 'co to jest drukarka do kawy',
        },
        audience_hint: 'Kategori arayışındaki alıcı — "coffee printer" jenerik terimini Google\'a yazan kişi; CAFEPASTE\'i kategorinin tanımı olarak sun',
        notes: 'Rakip-terim yakalama. Slug EN tarafında düz "coffee-printer".',
    },
    {
        id: 'glossary-coffee-printing-machine',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Coffee Printing Machine / Kahve Baskı Makinesi',
        slug: {
            tr: 'kahve-baski-makinesi',
            en: 'coffee-printing-machine',
            de: 'kaffee-druck-maschine',
            fr: 'machine-impression-cafe',
            es: 'maquina-impresion-cafe',
            it: 'macchina-stampa-caffe',
            pl: 'maszyna-do-druku-na-kawie',
        },
        target_query: {
            tr: 'kahve baskı makinesi nedir',
            en: 'what is a coffee printing machine',
            de: 'was ist eine Kaffee-Druckmaschine',
            fr: 'qu\'est-ce qu\'une machine d\'impression café',
            es: 'qué es una máquina de impresión de café',
            it: 'cos\'è una macchina per stampa caffè',
            pl: 'co to jest maszyna do druku na kawie',
        },
        audience_hint: 'TR\'de "kahve baskı makinesi" araması belirgin volume; coffee-printer\'dan farklı uzun-kuyruk',
        notes: 'Rakip-terim. coffee-printer ile karıştırma — bu daha "device" odaklı.',
    },
    {
        id: 'glossary-latte-art-printer',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Latte Art Printer / Latte Art Yazıcısı',
        slug: {
            tr: 'latte-art-yazicisi',
            en: 'latte-art-printer',
            de: 'latte-art-drucker',
            fr: 'imprimante-latte-art',
            es: 'impresora-latte-art',
            it: 'stampante-latte-art',
            pl: 'drukarka-latte-art',
        },
        target_query: {
            tr: 'latte art yazıcısı nedir',
            en: 'what is a latte art printer',
            de: 'was ist ein Latte-Art-Drucker',
            fr: 'qu\'est-ce qu\'une imprimante latte art',
            es: 'qué es una impresora latte art',
            it: 'cos\'è una stampante latte art',
            pl: 'co to jest drukarka latte art',
        },
        audience_hint: 'Mevcut "latte-art" glossary\'si kavramı tanımlıyor; bu sayfa CİHAZI tanımlar',
        notes: 'Rakip-terim. glossary-latte-art ile farkı: bu device.',
    },
    {
        id: 'glossary-cocktail-printer',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Cocktail Printer / Kokteyl Yazıcısı',
        slug: {
            tr: 'kokteyl-yazicisi',
            en: 'cocktail-printer',
            de: 'cocktail-drucker',
            fr: 'imprimante-cocktail',
            es: 'impresora-de-cocteles',
            it: 'stampante-cocktail',
            pl: 'drukarka-do-koktajli',
        },
        target_query: {
            tr: 'kokteyl yazıcısı nedir',
            en: 'what is a cocktail printer',
            de: 'was ist ein Cocktail-Drucker',
            fr: 'qu\'est-ce qu\'une imprimante à cocktail',
            es: 'qué es una impresora de cócteles',
            it: 'cos\'è una stampante per cocktail',
            pl: 'co to jest drukarka do koktajli',
        },
        audience_hint: 'Bar/restoran/event sektörü — kokteyl köpük baskısı kategori arayan kullanıcı',
        notes: 'Rakip-terim. Hotels & events solution sayfasına internal link öner.',
    },
    {
        id: 'glossary-selfie-coffee-printer',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Selfie Coffee Printer',
        slug: {
            tr: 'selfie-kahve-yazicisi',
            en: 'selfie-coffee-printer',
            de: 'selfie-kaffee-drucker',
            fr: 'imprimante-cafe-selfie',
            es: 'impresora-de-cafe-selfie',
            it: 'stampante-caffe-selfie',
            pl: 'drukarka-selfie-kawy',
        },
        target_query: {
            tr: 'selfie kahve yazıcısı nedir',
            en: 'what is a selfie coffee printer',
            de: 'was ist ein Selfie-Kaffeedrucker',
            fr: 'qu\'est-ce qu\'une imprimante café selfie',
            es: 'qué es una impresora de café selfie',
            it: 'cos\'è una stampante caffè selfie',
            pl: 'co to jest drukarka selfie do kawy',
        },
        audience_hint: 'Etkinlik/düğün sektörü — misafir fotoğrafını anında kahveye basan cihaz arayan kişi',
        notes: 'Rakip-terim. Wedding & event solution sayfasına internal link öner.',
    },
    {
        id: 'glossary-foam-printer',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Foam Printer / Köpük Yazıcısı',
        slug: {
            tr: 'kopuk-yazicisi',
            en: 'foam-printer',
            de: 'schaum-drucker',
            fr: 'imprimante-mousse',
            es: 'impresora-de-espuma',
            it: 'stampante-schiuma',
            pl: 'drukarka-do-pianki',
        },
        target_query: {
            tr: 'köpük yazıcısı nedir',
            en: 'what is a foam printer',
            de: 'was ist ein Schaumdrucker',
            fr: 'qu\'est-ce qu\'une imprimante à mousse',
            es: 'qué es una impresora de espuma',
            it: 'cos\'è una stampante per schiuma',
            pl: 'co to jest drukarka do pianki',
        },
        audience_hint: 'Teknik arayan alıcı — köpüklü içecek (kahve, bira, kokteyl) yüzeyine baskı yapan cihaz',
        notes: 'Rakip-terim. glossary-foam-printing süreci tanımlar, bu cihazı tanımlar.',
    },
    {
        id: 'glossary-beverage-art-creator',
        type: 'glossary',
        tier: 3,
        playbook: 'Dictionary',
        label: 'Beverage Art Creator / İçecek Art Makinesi',
        slug: {
            tr: 'icecek-art-makinesi',
            en: 'beverage-art-creator',
            de: 'getraenke-art-creator',
            fr: 'createur-art-boisson',
            es: 'creador-arte-bebida',
            it: 'creatore-arte-bevande',
            pl: 'kreator-art-napojow',
        },
        target_query: {
            tr: 'içecek art makinesi nedir',
            en: 'what is a beverage art creator',
            de: 'was ist ein Beverage Art Creator',
            fr: 'qu\'est-ce qu\'un créateur d\'art boisson',
            es: 'qué es un creador de arte para bebidas',
            it: 'cos\'è un creatore di beverage art',
            pl: 'co to jest kreator beverage art',
        },
        audience_hint: 'CAFEPASTE\'in en yakın kategori-tanımlayıcı terim — geniş kapsam (kahve + kokteyl + köpüklü içecek)',
        notes: 'Rakip-terim. Ana sayfa H1\'i ile aynı kavram — internal link homepage\'e.',
    },
];

// ----------------------------------------------------------------------------
// Tier 0 — Yayında (Wave 1)
// 12 sayfa zaten production'da: 10 TR sözlük + 2 TR rehber (manifesto + seçim).
// Bu tier roadmap UI'da YAYINDA olan içerikleri tek bir kategoride gösterir;
// kullanıcı buradan tek tıkla "Tüm dillere çevir" akışını başlatır.
//
// NOT: Diğer dillerin slug'ları AI çeviri çıktısına göre değişebilir; bu
// placeholder'lar gerçek slug'ları onaylandıktan sonra manuel güncellenir.
// ----------------------------------------------------------------------------

const TIER_0: RoadmapEntry[] = [
    // --- Glossary (10 sayfa) ---
    {
        id: 't0-glossary-latte-art-baskisi',
        type: 'glossary',
        tier: 0,
        playbook: 'Glossary',
        label: 'Latte Art Baskı',
        slug: { tr: 'latte-art-baskisi', en: 'latte-art-printing', de: 'latte-art-druck', fr: 'impression-latte-art', es: 'impresion-latte-art', it: 'stampa-latte-art', pl: 'druk-latte-art' },
        target_query: {
            tr: 'latte art baskı nedir',
            en: 'what is latte art printing',
            de: 'was ist Latte-Art-Druck',
            fr: 'quest-ce que limpression latte art',
            es: 'qué es la impresión de latte art',
            it: 'cosè la stampa latte art',
            pl: 'czym jest druk latte art',
        },
        audience_hint: 'Pazar terimi, en yaygın arama — TR\'de canlıda',
    },
    {
        id: 't0-glossary-icecek-sanat-makinesi',
        type: 'glossary',
        tier: 0,
        playbook: 'Glossary',
        label: 'İçecek Sanat Makinesi (TR karşılığı)',
        // TR slug ayrı (TR pazarı için yerel kategori adı). Diğer 6 dilin
        // hepsi 'beverage-art-creator' slug'ına işaret eder — bu kavram
        // EN ve diğer dillerde tek bir isimle ('Beverage Art Creator')
        // anılır, operatör kararı: uluslararası marka adı çevrilmez.
        slug: { tr: 'icecek-sanat-makinesi', en: 'beverage-art-creator', de: 'beverage-art-creator', fr: 'beverage-art-creator', es: 'beverage-art-creator', it: 'beverage-art-creator', pl: 'beverage-art-creator' },
        target_query: {
            tr: 'içecek sanat makinesi nedir',
            en: 'what is a beverage art creator',
            de: 'was ist ein Beverage Art Creator',
            fr: 'quest-ce quun beverage art creator',
            es: 'qué es un beverage art creator',
            it: 'cosè un beverage art creator',
            pl: 'czym jest beverage art creator',
        },
        audience_hint: 'TR pazarı için yerel kategori adı; diğer 6 dilde uluslararası "Beverage Art Creator" terimine işaret eder.',
    },
    {
        id: 't0-glossary-beverage-art-creator',
        type: 'glossary',
        tier: 0,
        playbook: 'Glossary',
        label: 'Beverage Art Creator (uluslararası kategori adı)',
        // CAFEPASTE'in icat ettiği uluslararası kategori adı. Tüm dillerde
        // aynı slug — uluslararası marka terimi olarak çevrilmez. TR sayfa
        // bu terimi açıklar; EN/DE/FR/ES/IT/PL sayfaları aynı slug üzerinde
        // dile özgü içerik taşır.
        slug: { tr: 'beverage-art-creator', en: 'beverage-art-creator', de: 'beverage-art-creator', fr: 'beverage-art-creator', es: 'beverage-art-creator', it: 'beverage-art-creator', pl: 'beverage-art-creator' },
        target_query: {
            tr: 'beverage art creator nedir',
            en: 'what is a beverage art creator',
            de: 'was ist ein Beverage Art Creator',
            fr: 'quest-ce quun beverage art creator',
            es: 'qué es un beverage art creator',
            it: 'cosè un beverage art creator',
            pl: 'czym jest beverage art creator',
        },
        audience_hint: 'Uluslararası kategori adı — TR\'de de Beverage Art Creator olarak öğretilir.',
    },
    {
        id: 't0-glossary-yenilebilir-murekkep',
        type: 'glossary',
        tier: 0,
        playbook: 'Glossary',
        label: 'Yenilebilir Mürekkep',
        slug: { tr: 'yenilebilir-murekkep', en: 'edible-ink', de: 'essbare-tinte', fr: 'encre-comestible', es: 'tinta-comestible', it: 'inchiostro-commestibile', pl: 'jadalny-atrament' },
        target_query: {
            tr: 'yenilebilir mürekkep nedir',
            en: 'what is edible ink',
            de: 'was ist essbare Tinte',
            fr: 'quest-ce que lencre comestible',
            es: 'qué es la tinta comestible',
            it: 'cosè linchiostro commestibile',
            pl: 'czym jest jadalny atrament',
        },
        audience_hint: 'Gıda güvenliği endişesi, allerjen sorusu',
    },
    {
        id: 't0-glossary-kopuk-baskisi',
        type: 'glossary',
        tier: 0,
        playbook: 'Glossary',
        label: 'Köpük Baskı',
        slug: { tr: 'kopuk-baskisi', en: 'foam-printing', de: 'schaumdruck', fr: 'impression-sur-mousse', es: 'impresion-sobre-espuma', it: 'stampa-sulla-schiuma', pl: 'druk-na-piance' },
        target_query: {
            tr: 'köpük baskı nedir',
            en: 'what is foam printing',
            de: 'was ist Schaumdruck',
            fr: 'quest-ce que limpression sur mousse',
            es: 'qué es la impresión sobre espuma',
            it: 'cosè la stampa sulla schiuma',
            pl: 'czym jest druk na piance',
        },
        audience_hint: 'Teknik süreç sorgusu',
    },
    {
        id: 't0-glossary-qr-bardak-sistemi',
        type: 'glossary',
        tier: 0,
        playbook: 'Glossary',
        label: 'QR Bardak Sistemi',
        slug: { tr: 'qr-bardak-sistemi', en: 'qr-cup-system', de: 'qr-becher-system', fr: 'systeme-verre-qr', es: 'sistema-vaso-qr', it: 'sistema-bicchiere-qr', pl: 'system-kubka-qr' },
        target_query: {
            tr: 'qr bardak sistemi nasıl çalışır',
            en: 'how does qr cup system work',
            de: 'wie funktioniert das QR-Becher-System',
            fr: 'comment fonctionne le système qr verre',
            es: 'cómo funciona el sistema de vaso qr',
            it: 'come funziona il sistema bicchiere qr',
            pl: 'jak działa system kubka qr',
        },
        audience_hint: 'CAFEPASTE operasyonel akış adı, biz icat ettik',
    },
    {
        id: 't0-glossary-bardak-markalama',
        type: 'glossary',
        tier: 0,
        playbook: 'Glossary',
        label: 'Bardak Markalama',
        slug: { tr: 'bardak-markalama', en: 'cup-branding', de: 'becher-branding', fr: 'branding-sur-verre', es: 'branding-en-vaso', it: 'branding-su-bicchiere', pl: 'branding-na-kubku' },
        target_query: {
            tr: 'bardak markalama nedir',
            en: 'what is cup branding',
            de: 'was ist Becher-Branding',
            fr: 'quest-ce que le branding sur verre',
            es: 'qué es el branding en vaso',
            it: 'cosè il branding su bicchiere',
            pl: 'czym jest branding na kubku',
        },
        audience_hint: 'Marka etkileşimi — pazarlama açısı',
    },
    {
        id: 't0-glossary-icecek-kisisellestirme',
        type: 'glossary',
        tier: 0,
        playbook: 'Glossary',
        label: 'İçecek Kişiselleştirme',
        slug: { tr: 'icecek-kisisellestirme', en: 'drink-personalization', de: 'getraenke-personalisierung', fr: 'personnalisation-boisson', es: 'personalizacion-bebida', it: 'personalizzazione-bevanda', pl: 'personalizacja-napoju' },
        target_query: {
            tr: 'içecek kişiselleştirme nedir',
            en: 'what is drink personalization',
            de: 'was ist Getränke-Personalisierung',
            fr: 'quest-ce que la personnalisation de boisson',
            es: 'qué es la personalización de bebida',
            it: 'cosè la personalizzazione della bevanda',
            pl: 'czym jest personalizacja napoju',
        },
        audience_hint: 'Müşteri deneyimi katmanı — QR sistem ile bağlı',
    },
    {
        id: 't0-glossary-kahveye-logo-baskisi',
        type: 'glossary',
        tier: 0,
        playbook: 'Glossary',
        label: 'Kahveye Logo Baskı',
        slug: { tr: 'kahveye-logo-baskisi', en: 'coffee-logo-printing', de: 'logo-druck-auf-kaffee', fr: 'impression-logo-cafe', es: 'impresion-logo-cafe', it: 'stampa-logo-caffe', pl: 'druk-logo-na-kawie' },
        target_query: {
            tr: 'kahveye logo baskı nasıl yapılır',
            en: 'how to print logo on coffee',
            de: 'wie druckt man ein Logo auf Kaffee',
            fr: 'comment imprimer un logo sur le café',
            es: 'cómo imprimir un logo en el café',
            it: 'come stampare un logo sul caffè',
            pl: 'jak drukować logo na kawie',
        },
        audience_hint: 'Marka aktivasyonu sorgusu',
    },
    {
        id: 't0-glossary-kahve-uzerine-fotograf-baskisi',
        type: 'glossary',
        tier: 0,
        playbook: 'Glossary',
        label: 'Kahve Üzerine Fotoğraf Baskısı',
        slug: { tr: 'kahve-uzerine-fotograf-baskisi', en: 'photo-printing-on-coffee', de: 'fotodruck-auf-kaffee', fr: 'impression-photo-sur-cafe', es: 'impresion-foto-en-cafe', it: 'stampa-foto-sul-caffe', pl: 'druk-zdjec-na-kawie' },
        target_query: {
            tr: 'kahve üzerine fotoğraf baskısı',
            en: 'photo printing on coffee',
            de: 'Fotodruck auf Kaffee',
            fr: 'impression photo sur café',
            es: 'impresión de fotos en café',
            it: 'stampa foto sul caffè',
            pl: 'drukowanie zdjęć na kawie',
        },
        audience_hint: 'Düğün, doğum günü, özel gün sorguları — yüksek hacim',
    },
    // --- Guide (2 sayfa) ---
    {
        id: 't0-guide-icecek-sanat-baskisi-rehber',
        type: 'guide',
        tier: 0,
        playbook: 'Glossary',
        label: 'İçecek Sanat Baskısı — Kapsamlı Rehber (Manifesto)',
        slug: { tr: 'icecek-sanat-baskisi-rehber', en: 'beverage-art-printing-guide', de: 'getraenkekunst-druck-leitfaden', fr: 'guide-impression-art-boisson', es: 'guia-impresion-arte-bebida', it: 'guida-stampa-beverage-art', pl: 'przewodnik-druku-beverage-art' },
        target_query: {
            tr: 'içecek sanat baskısı kapsamlı rehber',
            en: 'beverage art printing complete guide',
            de: 'Getränkekunst-Druck umfassender Leitfaden',
            fr: 'guide complet impression art boisson',
            es: 'guía completa de impresión arte bebida',
            it: 'guida completa stampa beverage art',
            pl: 'kompletny przewodnik drukowania beverage art',
        },
        audience_hint: 'Manifesto — kategori tanımı + 6-nokta + teknik özellikler',
        notes: 'Ana cite kaynağı; AI buying-research sorgularında öne çıkar.',
    },
    {
        id: 't0-guide-icecek-sanat-makinesi-nasil-secilir',
        type: 'guide',
        tier: 0,
        playbook: 'Glossary',
        label: 'İçecek Sanat Makinesi Nasıl Seçilir — 7 Kriter',
        slug: { tr: 'icecek-sanat-makinesi-nasil-secilir', en: 'how-to-choose-beverage-art-machine', de: 'getraenkekunst-maschine-auswaehlen', fr: 'choisir-machine-art-boisson', es: 'como-elegir-maquina-arte-bebidas', it: 'come-scegliere-macchina-beverage-art', pl: 'jak-wybrac-maszyne-beverage-art' },
        target_query: {
            tr: 'içecek sanat makinesi nasıl seçilir',
            en: 'how to choose a beverage art machine',
            de: 'wie wählt man eine Getränkekunst-Maschine',
            fr: 'comment choisir une machine art boisson',
            es: 'cómo elegir una máquina de arte para bebidas',
            it: 'come scegliere una macchina per beverage art',
            pl: 'jak wybrać maszynę do beverage art',
        },
        audience_hint: 'Buying-research — rakipsiz seçim rehberi, 7 kriter',
        notes: '8 soruluk üretici sorgu listesi içerir. Rakip adı geçmez.',
    },
    // --- Solution (4 sayfa — içerik dalgası 2) ---
    {
        id: 't0-solution-cafe-cozumu',
        type: 'solution',
        tier: 0,
        playbook: 'Personas',
        label: 'Kafe için içecek sanat baskısı',
        slug: { tr: 'cafe-cozumu', en: 'cafe-solution', de: 'cafe-loesung', fr: 'solution-cafe', es: 'solucion-cafeteria', it: 'soluzione-caffetteria', pl: 'rozwiazanie-kawiarni' },
        target_query: {
            tr: 'kafe için içecek sanat baskısı',
            en: 'beverage art printing for cafes',
            de: 'Getränkekunst-Druck für Cafés',
            fr: 'impression art boisson pour cafés',
            es: 'impresión arte bebida para cafeterías',
            it: 'stampa beverage art per caffè',
            pl: 'druk beverage art dla kawiarni',
        },
        audience_hint: 'Kafe sahipleri — günlük servis akışı, Pro vs Lite kararı, QR self-service',
        notes: 'TR yayında. Diğer dillerin slug\'ları AI çevirisi sonrası güncellenecek.',
    },
    {
        id: 't0-solution-otel-cozumu',
        type: 'solution',
        tier: 0,
        playbook: 'Personas',
        label: 'Otel ve resort için içecek sanat baskısı',
        slug: { tr: 'otel-cozumu', en: 'hotel-solution', de: 'hotel-loesung', fr: 'solution-hotel', es: 'solucion-hotel', it: 'soluzione-hotel', pl: 'rozwiazanie-hotelowe' },
        target_query: {
            tr: 'otel için içecek sanat baskısı',
            en: 'beverage art printing for hotels',
            de: 'Getränkekunst-Druck für Hotels',
            fr: 'impression art boisson pour hôtels',
            es: 'impresión arte bebida para hoteles',
            it: 'stampa beverage art per hotel',
            pl: 'druk beverage art dla hoteli',
        },
        audience_hint: 'Otel F&B müdürleri — kahvaltı, lobi barı, kurumsal etkinlik, 7 dilli misafir deneyimi',
        notes: 'TR yayında. Pro modeli standart — paralel iki bardak + 12 cm kek/pasta.',
    },
    {
        id: 't0-solution-etkinlik-dugun-cozumu',
        type: 'solution',
        tier: 0,
        playbook: 'Personas',
        label: 'Düğün ve etkinlik için içecek sanat baskısı',
        slug: { tr: 'etkinlik-dugun-cozumu', en: 'wedding-event-solution', de: 'hochzeit-event-loesung', fr: 'solution-mariage-evenement', es: 'solucion-boda-evento', it: 'soluzione-matrimonio-evento', pl: 'rozwiazanie-wesele-event' },
        target_query: {
            tr: 'düğün için içecek sanat baskısı',
            en: 'beverage art printing for weddings and events',
            de: 'Getränkekunst-Druck für Hochzeiten und Events',
            fr: 'impression art boisson pour mariages et événements',
            es: 'impresión arte bebida para bodas y eventos',
            it: 'stampa beverage art per matrimoni ed eventi',
            pl: 'druk beverage art dla wesel i wydarzeń',
        },
        audience_hint: 'Etkinlik organizatörleri ve çiftler — kiralama modeli, çift fotoğrafı, viral içerik',
        notes: 'TR yayında. Kiralama modeli baskın; Pro modeli paralel iki bardak + kek/pasta desteği.',
    },
    {
        id: 't0-solution-pastane-cozumu',
        type: 'solution',
        tier: 0,
        playbook: 'Personas',
        label: 'Pastane ve şekerleme atölyesi için CAFEPASTE Pro',
        slug: { tr: 'pastane-cozumu', en: 'bakery-solution', de: 'baeckerei-loesung', fr: 'solution-patisserie', es: 'solucion-pasteleria', it: 'soluzione-pasticceria', pl: 'rozwiazanie-cukierni' },
        target_query: {
            tr: 'pastane için kek baskı makinesi',
            en: 'cake printing machine for bakeries',
            de: 'Kuchen-Druckmaschine für Konditoreien',
            fr: 'machine impression gâteau pour pâtisseries',
            es: 'máquina impresión pastel para pastelerías',
            it: 'macchina stampa torte per pasticcerie',
            pl: 'maszyna do drukowania tortów dla cukierni',
        },
        audience_hint: 'Pastry chef ve pastane sahipleri — sadece Pro modeli, 12 cm kek/pasta, doğum günü ve kurumsal',
        notes: 'TR yayında. Lite uygun DEĞİL — sadece Pro modeli pastane operasyonu için doğru.',
    },
];

// Combined export. Order matters — roadmap UI renders in this order.
export const SEO_ROADMAP: RoadmapEntry[] = [...TIER_0, ...TIER_1, ...TIER_2, ...TIER_3];

export function getEntriesByTier(tier: Tier): RoadmapEntry[] {
    return SEO_ROADMAP.filter((e) => e.tier === tier);
}

export function findEntry(id: string): RoadmapEntry | undefined {
    return SEO_ROADMAP.find((e) => e.id === id);
}
